server:
    port: 8761

eureka:
    instance:
        prefer-ip-address: true
    client:
        registerWithEureka: false
        fetchRegistry: false

# При использовании данной опции недоступные клиенты удаляются из реестра даже
# в том случае, если отключен healthcheck. Подробнее о self-preservation режиме,
# см. https://github.com/Netflix/eureka/wiki/Understanding-Eureka-Peer-to-Peer-Communication
#    server:
#        enableSelfPreservation: false
